
ui: ui_MainWindow.py ui_ExplorationWindow.py ui_dialogphotos.py ui_NewMosaic.py


ui_MainWindow.py: mainwindow.ui
	pyuic5 -o $@ $<
	
ui_ExplorationWindow.py: explorationwindows.ui
	pyuic5 -o $@ $<
	
ui_dialogphotos.py: dialogphotos.ui
	pyuic5 -o $@ $<
	
ui_NewMosaic.py: NewMosaic.ui
	pyuic5 -o $@ $<
