# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewMosaic.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(588, 414)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setMinimumSize(QtCore.QSize(350, 0))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 362, 361))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.le_im_path = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.le_im_path.setObjectName("le_im_path")
        self.horizontalLayout_4.addWidget(self.le_im_path)
        self.pb_browse = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_browse.sizePolicy().hasHeightForWidth())
        self.pb_browse.setSizePolicy(sizePolicy)
        self.pb_browse.setObjectName("pb_browse")
        self.horizontalLayout_4.addWidget(self.pb_browse)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.groupBox_Tiles = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_Tiles.setEnabled(False)
        self.groupBox_Tiles.setObjectName("groupBox_Tiles")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_Tiles)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_Tiles)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.sb_im_h = QtWidgets.QSpinBox(self.groupBox)
        self.sb_im_h.setMinimum(1)
        self.sb_im_h.setObjectName("sb_im_h")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sb_im_h)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.sb_im_v = QtWidgets.QSpinBox(self.groupBox)
        self.sb_im_v.setMinimum(1)
        self.sb_im_v.setObjectName("sb_im_v")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sb_im_v)
        self.cb_keep_aspect_ratio = QtWidgets.QCheckBox(self.groupBox)
        self.cb_keep_aspect_ratio.setChecked(True)
        self.cb_keep_aspect_ratio.setObjectName("cb_keep_aspect_ratio")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cb_keep_aspect_ratio)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_Tiles)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.sb_tile_height = QtWidgets.QSpinBox(self.groupBox_3)
        self.sb_tile_height.setMinimum(2)
        self.sb_tile_height.setMaximum(500)
        self.sb_tile_height.setSingleStep(2)
        self.sb_tile_height.setProperty("value", 100)
        self.sb_tile_height.setObjectName("sb_tile_height")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sb_tile_height)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.sb_tile_width = QtWidgets.QSpinBox(self.groupBox_3)
        self.sb_tile_width.setMinimum(3)
        self.sb_tile_width.setMaximum(750)
        self.sb_tile_width.setSingleStep(3)
        self.sb_tile_width.setProperty("value", 150)
        self.sb_tile_width.setObjectName("sb_tile_width")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sb_tile_width)
        self.verticalLayout_6.addLayout(self.formLayout)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.verticalLayout_2.addWidget(self.groupBox_Tiles)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.lb_Image = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_Image.sizePolicy().hasHeightForWidth())
        self.lb_Image.setSizePolicy(sizePolicy)
        self.lb_Image.setMinimumSize(QtCore.QSize(100, 100))
        self.lb_Image.setMaximumSize(QtCore.QSize(200, 200))
        self.lb_Image.setText("")
        self.lb_Image.setScaledContents(False)
        self.lb_Image.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_Image.setObjectName("lb_Image")
        self.horizontalLayout_2.addWidget(self.lb_Image)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pb_cancel = QtWidgets.QPushButton(Dialog)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout.addWidget(self.pb_cancel)
        self.pb_ok = QtWidgets.QPushButton(Dialog)
        self.pb_ok.setEnabled(False)
        self.pb_ok.setObjectName("pb_ok")
        self.horizontalLayout.addWidget(self.pb_ok)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Source image :"))
        self.pb_browse.setText(_translate("Dialog", "Browse..."))
        self.groupBox_Tiles.setTitle(_translate("Dialog", "Tiles"))
        self.groupBox.setTitle(_translate("Dialog", "Number of tiles"))
        self.label_4.setText(_translate("Dialog", "Horizontaly :"))
        self.label_5.setText(_translate("Dialog", "Verticaly :"))
        self.cb_keep_aspect_ratio.setText(_translate("Dialog", "keep image ratio"))
        self.label_3.setText(_translate("Dialog", "Ratio :"))
        self.groupBox_3.setTitle(_translate("Dialog", "Size of tiles"))
        self.label.setText(_translate("Dialog", "Height :"))
        self.sb_tile_height.setSuffix(_translate("Dialog", " px"))
        self.label_6.setText(_translate("Dialog", "Width :"))
        self.sb_tile_width.setSuffix(_translate("Dialog", " px"))
        self.pb_cancel.setText(_translate("Dialog", "Cancel"))
        self.pb_ok.setText(_translate("Dialog", "Ok"))

